## Numpy 연습문제3

**numpy 모듈 선언**

In [1]:
import numpy as np

------

### 연습문제. 마스크 인덱싱

In [2]:
names = np.array(['Beomwoo','Beomwoo','Kim','Joan','Lee','Beomwoo',
                  'Park','Beomwoo'])
data = np.random.randn(8,4)  # 표준정규분포난수

In [3]:
data

array([[-1.23935801,  0.33262689,  0.98164676,  1.03131776],
       [ 0.42654504, -1.11717199,  1.30278561,  0.5858602 ],
       [ 0.24551938,  0.30510107,  0.60316697, -0.25536508],
       [ 0.71930313, -1.70829299, -1.20120615, -0.79094335],
       [ 1.00557288, -0.93830943, -0.13114645,  0.50180833],
       [ 0.38504503, -0.54561827,  0.68779731, -0.50151994],
       [-0.74182139, -1.0958868 , -0.26641613, -0.29195042],
       [ 0.22406243,  0.22095827, -0.92288202,  0.28752479]])

#### 문제1. data array에서 0번째 열이 0보다 작은 행 데이터 가져오기

In [4]:
data[data[:,0] < 0]

array([[-1.23935801,  0.33262689,  0.98164676,  1.03131776],
       [-0.74182139, -1.0958868 , -0.26641613, -0.29195042]])

#### 문제2. data array에서 0번째 열이 0보다 작은 행의 2, 3번째 열 데이터 가져오기

In [5]:
data[data[:,0] < 0, 2:]

array([[ 0.98164676,  1.03131776],
       [-0.26641613, -0.29195042]])

#### 문제3. data array에서 0번째 열이 0보다 작은 값을 갖는 사람은 누구인가?

In [6]:
names[data[:,0] < 0]

array(['Beomwoo', 'Park'], dtype='<U7')

#### 문제4. data array에서 2번째 열이 0보다 큰 값을 갖는 사람은 누구인가?

In [10]:
names[data[:,2] > 0]

array(['Beomwoo', 'Beomwoo', 'Kim', 'Beomwoo'], dtype='<U7')

----------------------------------------------

### 연습문제: 정렬

In [7]:
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

#### 문제1. 위 행렬에서 성적의 오름차순으로 학생의 이름을 출력하시오.

In [8]:
name_array[np.argsort(score_array)]

array(['John', 'Sarah', 'Samuel', 'Mike', 'Kate'], dtype='<U6')

#### 문제1-1. 성적의 내림차순으로 학생의 이름을 출력하시오.

In [11]:
name_array[np.argsort(score_array)][::-1]

array(['Kate', 'Mike', 'Samuel', 'Sarah', 'John'], dtype='<U6')

#### 문제2. 성적이 가장 좋은 사람의 이름을 출력하시오

In [9]:
name_array[np.argsort(score_array)[-1]]

'Kate'

In [12]:
name_array[np.argsort(score_array)][-1]

'Kate'

In [13]:
name_array[score_array == np.max(score_array)]

array(['Kate'], dtype='<U6')

--------