<img src='img/1_numpy.png' width=50 style='float:left'>

# NumPy

**numpy 모듈 선언**

In [1]:
import numpy as np

# 3. Array 인덱싱(indexing)과 슬라이싱(Slicing)

- 인덱싱(indexing) : 배열의 위치나 조건을 지정해 배열의 원소를 선택하는 것
- 슬라이싱(slicing) : 범위를 지정해 배열의 원소를 선택하는 것

## (1) Array 인덱싱

### 1차원 배열의 인덱싱

**배열명[위치]**


- 파이썬의 인덱싱과 동일
- 0번째로 시작함

In [2]:
arr1 = np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
# 0번째 요소
arr1[0]

1

In [5]:
# 3번째 요소
arr1[3]

4

In [6]:
# 마지막 요소
arr1[-1]

10

**배열명[[위치1, 위치2, ... ,위치n]]** 

In [7]:
# 1,3,4번 위치 요소
arr1[[1,3,4]]

array([2, 4, 5])

### 2차원 배열의 인덱싱
**배열명[행위치, 열위치]**

In [8]:
arr2 = np.arange(1,13).reshape(3,4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
# 2차원 행렬에서 인덱싱을 위해 2개의 인자를 [행, 열] 로 구분해서 참조
arr2[1,2]

7

In [10]:
# 2차원 행렬에서 인덱싱을 위해 2개의 인자를 [행][열] 두 개 사용해서 참조
arr2[1][2]

7

In [12]:
arr2[-1,-1]

12

**2차원배열명[행위치]**

: 2차원 배열에서 지정한 행 전체가 선택됨

In [13]:
arr2[1]

array([5, 6, 7, 8])

**2차원 배열의 특정 행을 지정해서 행 전체를 변경**

In [15]:
arr2[1] = np.array([100,110,120,130])
arr2

array([[  1,   2,   3,   4],
       [100, 110, 120, 130],
       [  9,  10,  11,  12]])

**배열명[[행위치1, 행위치2, ..., 행위치n],[열위치1, 열위치2,...,열위치n]]**

: 지정한 (행위치1, 열위치1), (행위치2, 열위치2), ... ,(행위치n, 열위치n)의 원소를 가진 행렬을 반환 

In [17]:
arr2[[1,2],[1,2]]

array([110,  11])

### 배열명[조건]

: 배열에서 조건을 만족하는 원소만 선택

In [18]:
arr2

array([[  1,   2,   3,   4],
       [100, 110, 120, 130],
       [  9,  10,  11,  12]])

In [19]:
# 10보다 큰 요소
arr2 > 10

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [False, False,  True,  True]])

In [20]:
arr2[arr2 > 10]

array([100, 110, 120, 130,  11,  12])

## (2) Array Slicing

### 1차원 배열의 슬라이싱(Slicing)

**배열[시작위치:끝위치]**

: 시작위치에서 끝위치-1 에 해당하는 배열의 원소를 반환

In [21]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
# 3번에서 8번까지의 요소
arr1[3:8]

array([4, 5, 6, 7, 8])

**배열[:끝위치]**

: 처음부터 '끝위치-1' 원소 반환

In [23]:
arr1[:6]

array([1, 2, 3, 4, 5, 6])

**배열[시작위치:]**

: 시작위치부터 마지막 원소까지 반환

In [24]:
arr1[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

**배열[:]**

: 모든 원소 반환

In [25]:
arr1[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**배열[start:stop:step]**

In [26]:
arr1[2:6:2]

array([3, 5])

In [27]:
arr1[::2]

array([1, 3, 5, 7, 9])

In [28]:
arr1[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

### 2차원 배열의 슬라이싱

**배열[행시작위치:행끝위치, 열시작위치:열끝위치]**

In [29]:
arr2

array([[  1,   2,   3,   4],
       [100, 110, 120, 130],
       [  9,  10,  11,  12]])

In [30]:
# 2행의 모든 요소
arr2[2]

array([ 9, 10, 11, 12])

In [31]:
# 2행의 모든 요소
arr2[2,:]

array([ 9, 10, 11, 12])

In [32]:
# 3열의 모든 요소
arr2[:,3]

array([  4, 130,  12])

In [33]:
arr2[1:3,0:2]

array([[100, 110],
       [  9,  10]])

**배열[행위치][열시작위치:열끝위치]**

: 특정 행을 선택한 후 열을 슬라이싱

In [35]:
arr2[1][0:2]

array([100, 110])

**슬라이싱 된 배열에 값을 지정**

In [36]:
arr2[1][0:2] = np.array([-10,-20])
arr2

array([[  1,   2,   3,   4],
       [-10, -20, 120, 130],
       [  9,  10,  11,  12]])

## (3) Array boolean 인덱싱(Mask)

- 다차원의 인덱싱을 응용하여 boolean 인덱싱
- boolean인덱싱을 통해 만들어낸 array를 통해 원하는 행 또는 열의 값만 뽑아냄
- 가리고 싶은 부분은 가리고, 원하는 요소만 꺼냄

In [37]:
names = np.array(['Beomwoo','Beomwoo','Kim','Joan','Lee','Beomwoo',
                  'Park','Beomwoo'])
names

array(['Beomwoo', 'Beomwoo', 'Kim', 'Joan', 'Lee', 'Beomwoo', 'Park',
       'Beomwoo'], dtype='<U7')

In [38]:
names.shape

(8,)

In [39]:
# np.random.randn(8,4) : 표준정규분포를 하는 난수발생 N(0, 1) 
# (평균은 0, 표준편차 1)
data = np.random.randn(8,4)
data

array([[-0.31322561, -0.91059754,  0.03141185,  0.6911534 ],
       [-0.76355313,  0.86776372,  0.46178881,  0.30278198],
       [ 0.87767734, -0.82135726, -1.05777813,  1.43641933],
       [ 1.2137764 , -1.04595047,  2.09131531,  0.78801228],
       [ 0.329538  , -0.4315478 , -0.44241753,  0.17853855],
       [ 0.6689687 ,  0.69106466, -0.11977171,  1.27577097],
       [ 0.60692682,  0.86666478,  0.1912165 , -0.77950953],
       [ 1.30155239,  0.11316635,  0.50630043,  0.16814731]])

In [40]:
names.shape, data.shape

((8,), (8, 4))

In [41]:
names == 'Beomwoo'

array([ True,  True, False, False, False,  True, False,  True])

In [42]:
# 요소가 Beomwoo인 항목에 대한 mask 생성
mask = names == 'Beomwoo'
mask

array([ True,  True, False, False, False,  True, False,  True])

In [43]:
# Beomwoo 데이터만 가져오기
data[mask]

array([[-0.31322561, -0.91059754,  0.03141185,  0.6911534 ],
       [-0.76355313,  0.86776372,  0.46178881,  0.30278198],
       [ 0.6689687 ,  0.69106466, -0.11977171,  1.27577097],
       [ 1.30155239,  0.11316635,  0.50630043,  0.16814731]])

In [46]:
# Kim의 data 가져오기
data[names =='Kim']

array([[ 0.87767734, -0.82135726, -1.05777813,  1.43641933]])

In [47]:
# Kim의 data 가져오기
data[names =='Kim', 0:2]

array([[ 0.87767734, -0.82135726]])

In [49]:
# Kim 또는 Park의 데이터 가져오기
(names == 'Kim') | (names =='Park')

array([False, False,  True, False, False, False,  True, False])

In [50]:
data[(names == 'Kim') | (names =='Park')]

array([[ 0.87767734, -0.82135726, -1.05777813,  1.43641933],
       [ 0.60692682,  0.86666478,  0.1912165 , -0.77950953]])

## (4) Fancy 인덱싱

- 배열에 리스트나 ndarray로 인덱스 집합을 지정하여 요소 참조

In [52]:
arr = np.arange(1,25).reshape(4,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [54]:
arr[0,0], arr[1,1], arr[2,2], arr[3,3]

(1, 8, 15, 22)

In [55]:
[arr[0,0], arr[1,1], arr[2,2], arr[3,3]]

[1, 8, 15, 22]

In [56]:
arr[[0,1,2,3,],[0,1,2,3]]

array([ 1,  8, 15, 22])

In [57]:
arr[1:3, 0:2]

array([[ 7,  8],
       [13, 14]])

In [58]:
arr[:,[1,2]]

array([[ 2,  3],
       [ 8,  9],
       [14, 15],
       [20, 21]])

-------