## Numpy 연습문제3

**numpy 모듈 선언**

In [1]:
import numpy as np

------

### 연습문제. 마스크 인덱싱

In [2]:
names = np.array(['Beomwoo','Beomwoo','Kim','Joan','Lee','Beomwoo',
                  'Park','Beomwoo'])
data = np.random.randn(8,4)  # 표준정규분포난수

In [3]:
data

array([[ 1.55758371,  1.30821181, -1.49322237,  0.50441545],
       [ 1.54512667, -2.60315643,  0.18386882,  0.31632373],
       [ 0.91585114, -0.01718867,  1.69454942,  0.17514947],
       [ 0.89784376,  1.3819088 ,  0.18936342,  1.18424545],
       [-1.09067602, -1.59614712,  0.54581826, -0.62361423],
       [-0.20702439,  0.17272167, -1.3984963 ,  0.59771905],
       [ 1.6479234 , -1.1141389 ,  1.80078108,  0.90190899],
       [-1.04309957, -0.08678482,  1.29905951,  0.66283558]])

#### 문제1. data array에서 0번째 열이 0보다 작은 행 데이터 가져오기

In [12]:
data[data[:,0] < 0]

array([[-1.09067602, -1.59614712,  0.54581826, -0.62361423],
       [-0.20702439,  0.17272167, -1.3984963 ,  0.59771905],
       [-1.04309957, -0.08678482,  1.29905951,  0.66283558]])

#### 문제2. data array에서 0번째 열이 0보다 작은 행의 2, 3번째 열 데이터 가져오기

In [14]:
data[data[:,0] < 0, 2:]

array([[ 0.54581826, -0.62361423],
       [-1.3984963 ,  0.59771905],
       [ 1.29905951,  0.66283558]])

----------------------------------------------

### 연습문제: 정렬

In [4]:
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

#### 문제1. 위 행렬에서 성적의 오름차순으로 학생의 이름을 출력하시오.

In [7]:
name_array[np.argsort(score_array)]

array(['John', 'Sarah', 'Samuel', 'Mike', 'Kate'], dtype='<U6')

#### 문제2. 성적이 가장 좋은 사람의 이름을 출력하시오

In [10]:
name_array[np.argsort(score_array)[-1]]

'Kate'

--------