<img src='img/1_numpy.png' width=50 style='float:left'>

# NumPy

**numpy 모듈 선언**

In [1]:
import numpy as np

## 4. Array의 정렬 : sort(), argsort()

- **sort() : 행렬 정렬**
- **argsort() : 정렬된 행렬의 인덱스 반환**

https://numpy.org/doc/stable/reference/generated/numpy.sort.html#numpy.sort

**1차원 행렬 생성** 

In [11]:
arr = np.array([3,1,9,5,-1, 10])
arr

array([ 3,  1,  9,  5, -1, 10])

**sort()로 정렬**

- np.sort() : 원본 유지

In [7]:
sort_arr = np.sort(arr)
sort_arr

array([-1,  1,  3,  5,  9, 10])

In [8]:
arr

array([ 3,  1,  9,  5, -1, 10])

- sort() : 원본 변경

In [9]:
arr.sort()

In [10]:
arr

array([-1,  1,  3,  5,  9, 10])

**내림차순으로 정렬**

In [12]:
desc_arr = sort_arr[::-1]

In [13]:
desc_arr

array([10,  9,  5,  3,  1, -1])

**2차원 행렬의 정렬**

In [20]:
arr2 = np.array([[8,12,5],[-1,4, -5]])
arr2

array([[ 8, 12,  5],
       [-1,  4, -5]])

In [15]:
np.sort(arr2)

array([[ 5,  8, 12],
       [-5, -1,  4]])

In [21]:
np.sort(arr2, axis=0)

array([[-1,  4, -5],
       [ 8, 12,  5]])

**정렬된 행렬의 인덱스 반환: argsort()**

In [22]:
arr

array([ 3,  1,  9,  5, -1, 10])

In [23]:
np.argsort(arr)

array([4, 1, 0, 3, 2, 5], dtype=int64)

In [24]:
np.sort(arr)

array([-1,  1,  3,  5,  9, 10])

In [25]:
arr2

array([[ 8, 12,  5],
       [-1,  4, -5]])

In [26]:
np.argsort(arr2, axis=0)

array([[1, 1, 1],
       [0, 0, 0]], dtype=int64)

In [27]:
np.argsort(arr2, axis=1)

array([[2, 0, 1],
       [2, 0, 1]], dtype=int64)

In [28]:
names = np.array(['Beomwoo1','Beomwoo2','Kim','Joan','Lee','Beomwoo3',
                  'Park','Beomwoo4'])
names

array(['Beomwoo1', 'Beomwoo2', 'Kim', 'Joan', 'Lee', 'Beomwoo3', 'Park',
       'Beomwoo4'], dtype='<U8')

In [29]:
scores = np.array([50, 70, 100, 60, 82, 90, 85, 80])
scores

array([ 50,  70, 100,  60,  82,  90,  85,  80])

In [30]:
np.sort(scores)

array([ 50,  60,  70,  80,  82,  85,  90, 100])

In [32]:
names[np.argsort(scores)]

array(['Beomwoo1', 'Joan', 'Beomwoo2', 'Beomwoo4', 'Lee', 'Park',
       'Beomwoo3', 'Kim'], dtype='<U8')

In [35]:
# names를 오름차순으로 정렬한 scores
scores[np.argsort(names)]

array([ 50,  70,  90,  80,  60, 100,  82,  85])

----------

### numpy 공식 사이트의 API reference 사이트에서 다양한 함수들 참고

**numpy API Refernce**

https://numpy.org/doc/stable/reference/index.html

- 입출력(input/output) : https://numpy.org/doc/stable/reference/routines.io.html
- 선형대수 : https://numpy.org/doc/stable/reference/routines.linalg.html
- 난수 : https://numpy.org/doc/stable/reference/random/index.html
- 수학 : https://numpy.org/doc/stable/reference/routines.math.html
- 통계 : https://numpy.org/doc/stable/reference/routines.statistics.html

### NumPy의 모든 API는 np.info 함수를 이용 도움말 확인

**np.info(함수이름)**

In [37]:
np.info(np.sort)

 sort(a, axis=-1, kind=None, order=None)

Return a sorted copy of an array.

Parameters
----------
a : array_like
    Array to be sorted.
axis : int or None, optional
    Axis along which to sort. If None, the array is flattened before
    sorting. The default is -1, which sorts along the last axis.
kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
    Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
    and 'mergesort' use timsort or radix sort under the covers and, in general,
    the actual implementation will vary with data type. The 'mergesort' option
    is retained for backwards compatibility.

    .. versionchanged:: 1.15.0.
       The 'stable' option was added.

order : str or list of str, optional
    When `a` is an array with fields defined, this argument specifies
    which fields to compare first, second, etc.  A single field can
    be specified as a string, and not all fields need be specified,
    but unspecified fields will still b

In [38]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


#### 노트북에서 도움말 확인 단축키  : shift+Tap 키

In [ ]:
print()

------