<img src='img/1_numpy.png' width=50 style='float:left'>

# NumPy

In [1]:
import numpy as np

## array에 적용되는 다양한 함수

### 하나의 array에 적용되는 함수

**random.randn(d0,d1,.., dn) : 표준정규난수 생성**

: https://numpy.org/doc/stable/reference/random/legacy.html

In [8]:
arr1 = np.random.randn(10)
arr1

In [9]:
arr2 = np.random.randn(3,5)
arr2

array([[ 0.19169337, -0.9203267 ,  0.95183006, -1.54273192,  0.75343043],
       [-0.1151473 , -1.02238909, -0.76825215,  1.2027355 , -0.40492402],
       [ 0.62741737, -0.26494654,  1.18846496,  0.04691488, -1.83797749]])

In [6]:
np.random.randn(3,2,4)

array([[[-1.92207624,  0.96471099, -0.41596962,  1.15863678],
        [-0.84041647,  1.43282663, -1.91725348,  0.99263654]],

       [[ 0.56878839,  0.36516781,  1.79341773,  0.861013  ],
        [-0.38803872,  0.60610334,  1.2528399 ,  1.63701364]],

       [[ 0.15672935,  0.21909276, -1.02047652, -0.14988344],
        [ 0.68763497, -0.99077438,  0.17928531, -1.15620307]]])

In [7]:
np.random.random(5)

array([0.91922006, 0.47583019, 0.68134826, 0.48750874, 0.12968967])

**수학 관련 함수**

- 제곱근, 절대값, 삼각함수, 지수로그함수, 반올림함수 등

https://numpy.org/doc/stable/reference/routines.math.html

In [10]:
np.abs(arr1)

array([1.47008818, 1.30811046, 0.20127443, 1.17936493, 1.33845218,
       1.0130261 , 0.57774501, 0.01370461, 0.94774618, 0.19795817])

In [11]:
np.sqrt(np.abs(arr2))

array([[0.43782801, 0.95933659, 0.97561778, 1.2420676 , 0.8680037 ],
       [0.33933361, 1.01113258, 0.87649994, 1.09669299, 0.63633641],
       [0.79209682, 0.51472958, 1.0901674 , 0.21659843, 1.35572029]])

In [12]:
np.square(arr2)

array([[3.67463482e-02, 8.47001230e-01, 9.05980466e-01, 2.38002178e+00,
        5.67657412e-01],
       [1.32588999e-02, 1.04527946e+00, 5.90211360e-01, 1.44657269e+00,
        1.63963463e-01],
       [3.93652559e-01, 7.01966692e-02, 1.41244897e+00, 2.20100593e-03,
        3.37816127e+00]])

**지수함수**

In [13]:
np.exp(arr1)

array([0.22990521, 0.27033037, 0.817688  , 3.25230811, 0.26225127,
       0.36311848, 0.56116236, 0.98638887, 0.38761365, 0.82040417])

**로그함수**

- 자연로그 : log()
- 상용로그 : log10()
- 밑이2인 로그 : log2()

In [14]:
np.log(np.abs(arr1))

array([ 0.38532238,  0.2685837 , -1.60308597,  0.1649761 ,  0.29151385,
        0.01294199, -0.54862267, -4.29002323, -0.05366856, -1.61969951])

In [15]:
np.log10(np.abs(arr1))

array([ 0.16734338,  0.11664442, -0.69621139,  0.07164821,  0.12660286,
        0.00562063, -0.2382638 , -1.86313342, -0.02330796, -0.70342656])

In [16]:
np.log2(np.abs(arr1))

array([ 0.55590269,  0.38748437, -2.31276418,  0.2380102 ,  0.42056559,
        0.01867134, -0.79149521, -6.18919524, -0.07742736, -2.33673246])

**각 성분의 부호 계산 : sign()**

: +인 경우 1, -인 경우 -1, 0인 경우 0

In [17]:
arr1

array([-1.47008818, -1.30811046, -0.20127443,  1.17936493, -1.33845218,
       -1.0130261 , -0.57774501, -0.01370461, -0.94774618, -0.19795817])

In [18]:
np.sign(arr1)

array([-1., -1., -1.,  1., -1., -1., -1., -1., -1., -1.])

**반올림 함수**

In [19]:
# 소숫점 첫번째자리에서 내림
np.floor(arr1)

array([-2., -2., -1.,  1., -2., -2., -1., -1., -1., -1.])

In [20]:
np.ceil(arr1)

array([-1., -1., -0.,  2., -1., -1., -0., -0., -0., -0.])

In [21]:
np.fix(arr1)

array([-1., -1., -0.,  1., -1., -1., -0., -0., -0., -0.])

**NaN 여부 확인**

In [22]:
np.nan

nan

In [23]:
arr2

array([[ 0.19169337, -0.9203267 ,  0.95183006, -1.54273192,  0.75343043],
       [-0.1151473 , -1.02238909, -0.76825215,  1.2027355 , -0.40492402],
       [ 0.62741737, -0.26494654,  1.18846496,  0.04691488, -1.83797749]])

In [30]:
arr2[2,3] = np.nan
arr2

array([[ 0.19169337, -0.9203267 ,  0.95183006, -1.54273192,  0.75343043],
       [-0.1151473 , -1.02238909, -0.76825215,  1.2027355 , -0.40492402],
       [ 0.62741737, -0.26494654,  1.18846496,         nan, -1.83797749]])

In [31]:
np.isnan(arr2)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True, False]])

**무한대(inf) 확인**

In [32]:
np.inf

inf

In [33]:
np.isinf(arr2)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

**삼각함수**

: 각 성분에 대해 삼각함수 값을 계산하기(cos, cosh, sin, sinh, tan, tanh)

In [34]:
np.cos(arr1)

array([0.100538  , 0.25967522, 0.97981259, 0.38151194, 0.23025932,
       0.52929569, 0.83769631, 0.99990609, 0.5835149 , 0.98047018])

In [35]:
np.sin(arr1)

array([-0.99493322, -0.96569601, -0.1999182 ,  0.92436391, -0.97312931,
       -0.84843743, -0.54613633, -0.01370418, -0.81210243, -0.19666779])

**Sum, product, difference함수**

In [39]:
arr3 = np.random.randn(3,4)
arr3

array([[ 1.12858308, -0.82790334,  1.01569199,  0.27674421],
       [ 0.51369136, -2.33181213,  0.90714957, -2.19133761],
       [ 0.65840809, -2.53144186,  1.29883705, -0.52019245]])

In [40]:
np.sum(arr3)

-2.603582038150039

In [41]:
np.sum(arr3, axis=0)

array([ 2.30068253, -5.69115733,  3.22167861, -2.43478585])

In [42]:
np.sum(arr3, axis=1)

array([ 1.59311594, -3.10230881, -1.09438917])

**평균(mean), 표준편차(std), 분산(var)**

In [43]:
np.mean(arr3)

-0.21696516984583658

In [44]:
np.mean(arr3, axis=1)

array([ 0.39827899, -0.7755772 , -0.27359729])

In [45]:
np.std(arr3, axis=1)

array([0.77987766, 1.49332076, 1.45772555])

In [46]:
np.var(arr3, axis=1)

array([0.60820917, 2.23000688, 2.12496377])

**최대값(max), 최소값(min)**

In [48]:
np.max(arr3, axis=1)

array([1.12858308, 0.90714957, 1.29883705])

**최대값, 최소값 위치 인덱스 : argmax(), argmin()**

In [49]:
np.argmax(arr3, axis=1)

array([0, 2, 2], dtype=int64)

In [50]:
np.argmin(arr3, axis=0)

array([1, 2, 1, 1], dtype=int64)

**누적합(cumsum), 누적곱(cumprod)**

In [54]:
np.cumsum(arr1)

array([-1.47008818, -2.77819863, -2.97947307, -1.80010813, -3.13856031,
       -4.15158641, -4.72933142, -4.74303602, -5.6907822 , -5.88874038])

In [53]:
np.cumsum(arr3, axis=1)

array([[ 1.12858308,  0.30067974,  1.31637173,  1.59311594],
       [ 0.51369136, -1.81812077, -0.9109712 , -3.10230881],
       [ 0.65840809, -1.87303377, -0.57419672, -1.09438917]])

In [55]:
np.cumprod(arr1)

array([-1.47008818e+00,  1.92303772e+00, -3.87058323e-01, -4.56483013e-01,
        6.10980682e-01, -6.18939376e-01,  3.57589134e-01, -4.90061852e-03,
        4.64454248e-03, -9.19425148e-04])

In [56]:
np.cumprod(arr3, axis=0)

array([[ 1.12858308, -0.82790334,  1.01569199,  0.27674421],
       [ 0.57974337,  1.93051504,  0.92138456, -0.60643999],
       [ 0.38170773, -4.8869866 ,  1.1967284 ,  0.3154655 ]])

### 정렬 함수 : sort(), argsort()

In [57]:
np.sort(arr1)

array([-1.47008818, -1.33845218, -1.30811046, -1.0130261 , -0.94774618,
       -0.57774501, -0.20127443, -0.19795817, -0.01370461,  1.17936493])

In [58]:
np.argsort(arr1)

array([0, 4, 1, 5, 8, 6, 2, 9, 7, 3], dtype=int64)

### 두 개의 array에 적용되는 함수

In [59]:
arr3

array([[ 1.12858308, -0.82790334,  1.01569199,  0.27674421],
       [ 0.51369136, -2.33181213,  0.90714957, -2.19133761],
       [ 0.65840809, -2.53144186,  1.29883705, -0.52019245]])

In [60]:
arr4 = np.random.randn(3,4)
arr4

array([[ 1.2784876 ,  0.89768532,  0.0606342 ,  0.37219383],
       [ 0.66996626,  0.94241535,  0.83583845,  0.99865736],
       [ 0.80263993,  1.99835733, -0.34661542,  0.41862403]])

**두 개의 array에 대해 동일한 위치의 성분끼리 연산**

- add(), subtract(), multiply(), divide()

In [61]:
np.add(arr3, arr4)

array([[ 2.40707068,  0.06978199,  1.0763262 ,  0.64893804],
       [ 1.18365762, -1.38939678,  1.74298802, -1.19268025],
       [ 1.46104802, -0.53308454,  0.95222163, -0.10156842]])

In [63]:
np.divide(arr3, arr4)

array([[ 0.88274855, -0.92226453, 16.75113896,  0.74354862],
       [ 0.76674213, -2.47429345,  1.08531688, -2.19428374],
       [ 0.82030319, -1.26676137, -3.74719924, -1.24262444]])

- 최대값 또는 최소값 계산
: maximum(), minimum()

In [64]:
np.maximum(arr3, arr4)

array([[1.2784876 , 0.89768532, 1.01569199, 0.37219383],
       [0.66996626, 0.94241535, 0.90714957, 0.99865736],
       [0.80263993, 1.99835733, 1.29883705, 0.41862403]])

---------------------------