## Numpy 연습문제1

#### 1. np이름으로 numpy 패키지 가져오기

In [1]:
import numpy as np

#### 2. numpy 버전 출력하기

In [2]:
np.__version__

'1.21.5'

#### 3. 모두 0의 값을 갖는 사이즈가 10인 벡터 생성하기

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. 값 10~49를 갖는 벡터 생성하기

In [4]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 5. 4번에서 생성한 벡터 요소를 역순으로 갖는 벡터 출력하기 

#### 6. 0~8 사이의 정수 값을 3X3 크기로 갖는 행렬 생성하기 

In [7]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
np.random.randint(8,size=(3,3))

array([[4, 6, 3],
       [7, 6, 4],
       [0, 4, 5]])

#### 7. 실수 난수를 3X3X3의 크기로 갖는 배열 생성하기

In [6]:
np.random.rand(3,3,3)

array([[[0.18601966, 0.77055134, 0.24007976],
        [0.99099419, 0.68645493, 0.7349993 ],
        [0.78311665, 0.35697327, 0.97762891]],

       [[0.30145426, 0.69207623, 0.38478395],
        [0.74149719, 0.45951511, 0.55911483],
        [0.47393992, 0.65482603, 0.98833694]],

       [[0.7642018 , 0.07060519, 0.33520767],
        [0.73270446, 0.75771932, 0.22411276],
        [0.25870374, 0.25830416, 0.91240904]]])

#### 8. 모두 1의 요소를 갖는 5X3 크기 행렬과 3X2 크기 행렬의 곱의 결과는?

-----